---
- name: understand block, rescue and always
  hosts: ansible1
  tasks:
  - name: manage httpd
    block:
      - name: copy index.html
        copy:
          src: /tmp/index.html
          dest: /var/www/html/index.html
    rescue:
      - name: install httpd
        package:
          name: httpd
          state: installed
    always:
      - name: ensure httpd is started
        service:
          name: httpd
          state: restarted
