---
- name: Using the copy module
  hosts: rocky
  tasks:
  - name: copy users.txt 
    copy:
      src: users.txt
      dest: /tmp/users.txt
      owner: rishikap
      group: rishikap
      mode: 0644
      setype: samba_share_t
...
