---
- name: remove ftp
  hosts: rocky 
  tasks:
  - name: remove ftp package
    package:
      name: vsftpd
      state: absent
    notify:
      del_ftpindex

  handlers:
    - name: del_ftpindex
      file:
        path: /var/ftp/pub/dummy_file.txt
        state: absent
