---
- name: install httpd and run the service
  hosts: rocky
  tasks:
  - name: install web 
    package:
      name: httpd
      state: latest

  - name: copy content
    copy:
      src: index.html
      dest: /var/www/html/index.html

  - name: httpd start
    service:
      name: httpd
      state: started
      enabled: true
...
