---
- name: install apache server and open the ports 
  hosts: rocky
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: python3-PyMySQL
    rule: http
  tasks:
  - name: required package are installed and up to date
    package:
      name: 
        - "{{ web_pkg }}"
        - "{{ firewall_pkg }}"
        - "{{ python_pkg }}"
      state: latest

  - name: The {{ firewall_service }} service is started and enabled
    service:
      name: "{{ firewall_service }}"
      state: started
      enabled: true

  - name: The {{ web_service }} service is started and enabled
    service:
      name: "{{ web_service }}"
      state: started
      enabled: true

  - name: Web content is in place
    copy:
      content: "Example web content"
      dest: /var/www/html/index.html

  - name: The firewall port for {{ rule }} is open
    firewalld:
      service: "{{ rule }}"
      permanent: true
      immediate: true
      state: enabled 

- name: verify the apache service 
  hosts: localhost
  become: false
  tasks:
  - name: Ensure that webserver is reachable
    uri:
      url: http://ansible1.example.com
      status_code: 200
...
