---
- name: learn to use set_fact variable
  hosts: rocky
  tasks:
  - set_fact: 
      package: vsftpd
  - debug:
      msg: the value of package is {{ package }}
  - name: install package
    package:
      name: "{{ package }}"
      state: latest
