---
- hosts: all
  remote_user: root
  tasks:
  - name: Ensure the ntp package is installed 
    yum:
      name: ntp
      state: present
  - name: Ensure the ntp service is enabled and running
    service:
     name: ntpd
     state: started
     enabled: True
