---
- name: manage windows updates
  hosts:  all
  tasks:
    - name: windows_updates
      win_updates:
        log_path: c:\windows_update.txt
        category_names:
          - Application
          - Connectors
          - CriticalUpdates
          - DefinitionUpdates
          - DeveloperKits
          - FeaturePacks
          - Guidance
          - SecurityUpdates
          - ServicePacks
          - Tools
          - UpdateRollups
          - Updates
        reboot:	yes
        state:	installed
...
